#!/usr/bin/env node
// scripts/apply-i18n.mjs
// Reads a replacement map generated by extract-i18n.mjs and patches source files
// to replace hardcoded strings with t() calls, adding useTranslation where needed.

import { readFileSync, writeFileSync } from 'fs';
import { parseArgs } from 'util';

const { values: args } = parseArgs({
	options: { namespace: { type: 'string' } },
});

const namespace = args.namespace;
if (!namespace) {
	console.error('Usage: node scripts/apply-i18n.mjs --namespace <name>');
	process.exit(1);
}

const mapPath = `scripts/i18n-replacements/${namespace}.json`;
let replacements;
try {
	replacements = JSON.parse(readFileSync(mapPath, 'utf8'));
} catch {
	console.error(`Replacement map not found: ${mapPath}\nRun extract-i18n.mjs first.`);
	process.exit(1);
}

// Group by file, sort by line descending so replacements don't shift offsets
const byFile = {};
for (const r of replacements) {
	(byFile[r.file] ??= []).push(r);
}
for (const arr of Object.values(byFile)) {
	arr.sort((a, b) => b.line - a.line || b.col - a.col);
}

let totalApplied = 0;
const manualItems = [];

for (const [file, fileReplacements] of Object.entries(byFile)) {
	let content;
	try {
		content = readFileSync(file, 'utf8');
	} catch {
		console.warn(`  ⚠ Cannot read ${file} — skipping`);
		continue;
	}

	const lines = content.split('\n');
	const appliedInFile = [];

	for (const r of fileReplacements) {
		const { originalString, suggestedKey } = r;
		// Build the t() call — use namespace: prefix if key belongs to a different namespace
		const keyArg = suggestedKey.startsWith(`${namespace}.`)
			? `'${suggestedKey.slice(namespace.length + 1)}'`
			: `'${suggestedKey}'`; // cross-namespace key (common:actions.save handled by caller)

		const tCall = `t(${keyArg})`;
		const lineIdx = r.line - 1;
		const line = lines[lineIdx] ?? '';

		let replaced = false;

		// Pattern 1: JSX text node  >string<  →  >{t(key)}<
		if (line.includes(`>${originalString}<`)) {
			lines[lineIdx] = line.replace(`>${originalString}<`, `>{${tCall}}<`);
			replaced = true;
		}
		// Pattern 2: JSX expression  {'string'}  →  {t(key)}
		else if (line.includes(`{'${originalString}'}`)) {
			lines[lineIdx] = line.replace(`{'${originalString}'}`, `{${tCall}}`);
			replaced = true;
		}
		// Pattern 3: JSX expression  {"string"}  →  {t(key)}
		else if (line.includes(`{"${originalString}"}`)) {
			lines[lineIdx] = line.replace(`{"${originalString}"}`, `{${tCall}}`);
			replaced = true;
		}
		// Pattern 4: Attribute string  attr="string"  →  attr={t(key)}
		else if (line.includes(`="${originalString}"`)) {
			lines[lineIdx] = line.replace(`="${originalString}"`, `={${tCall}}`);
			replaced = true;
		}

		if (replaced) {
			appliedInFile.push(r);
			totalApplied++;
		} else {
			manualItems.push({ file, line: r.line, originalString, suggestedKey });
		}
	}

	if (!appliedInFile.length) continue;

	content = lines.join('\n');

	// Add useTranslation import if not already present
	if (!content.includes('useTranslation')) {
		// Insert after last import line
		content = content.replace(/((?:import .+\n)+)(?!import)/, `$1import { useTranslation } from 'react-i18next';\n`);
	}

	// Add const { t } = useTranslation('namespace') hook if not present
	// Heuristic: insert after the opening brace of the first arrow function component
	if (!content.includes(`useTranslation('${namespace}')`) && !content.includes(`useTranslation(["${namespace}`)) {
		const hookLine = `\n\tconst { t } = useTranslation('${namespace}');\n`;
		// Match: const ComponentName: FC<...> = (...) => {  OR  const ComponentName = (...) => {
		content = content.replace(
			/(const \w+ ?(?::\s*FC[^=]*)? ?= ?(?:\([^)]*\)) ?=> ?\{)/,
			`$1${hookLine}`,
		);
	}

	writeFileSync(file, content, 'utf8');
	console.log(`  ✓ ${file} — ${appliedInFile.length} replaced`);
}

console.log(`\nSummary: ${totalApplied} replacements applied`);

if (manualItems.length) {
	console.log(`\n⚠  ${manualItems.length} items need manual replacement:`);
	for (const item of manualItems) {
		console.log(`   ${item.file}:${item.line}  "${item.originalString}"  →  {t('${item.suggestedKey.slice(namespace.length + 1)}')}`);
	}
}

console.log(`
Next steps:
  1. Review changes:         git diff
  2. Fix manual items above
  3. Lint + format:          npx eslint src/ --fix
  4. Type check:             npx tsc --noEmit
  5. Verify in browser (en + ar)
  6. Commit:                 git add -A && git commit -m "feat(i18n): migrate ${namespace} namespace"
`);
